import { defineSegment } from "videowright";

let host: HTMLElement | null = null;

const CLAUDE_ORANGE = "#d97757";

// User-provided ASCII mascot
const MASCOT = `  ▐▛███▜▌
 ▝▜█████▛▘
   ▘▘ ▝▝`;

const USER_PROMPT_TEXT = `I want to build a video, here's the script:`;
const USER_PROMPT_PASTE = "[Pasted 43 lines]";
const AGENT_RESPONSE_1 = "Got it! Building the video now.";
const AGENT_RESPONSE_2 = "Video is ready. Preview: npm run dev";

export default defineSegment({
	id: "cold-open",
	advances: [7.0],
	voiceover:
		"The video you're watching and this voice were generated by Videowright in Claude Code, with a single prompt.",

	mount(el) {
		host = el;
		el.innerHTML = `
      <div style="
        position: relative;
        height: 100%;
        background: var(--color-bg);
        color: var(--color-fg);
        font-family: var(--font-body);
        overflow: hidden;
      ">
        <div style="
          position: absolute; inset: 0; pointer-events: none;
          background:
            linear-gradient(var(--grid-line) 1px, transparent 1px) 0 0 / 64px 64px,
            linear-gradient(90deg, var(--grid-line) 1px, transparent 1px) 0 0 / 64px 64px;
        "></div>

        <!-- Generic terminal window — standard dark terminal colors -->
        <div data-ref="terminal" style="
          position: absolute;
          left: 50%; top: 50%;
          width: 1680px; height: 900px;
          transform: translate(-50%, -50%);
          background: #0c0c0c;
          border: 1px solid #2a2a2a;
          border-radius: 8px;
          box-shadow: 0 30px 80px rgba(0,0,0,0.7);
          display: flex; flex-direction: column;
          opacity: 0;
          overflow: hidden;
        ">
          <!-- Standard terminal chrome (dark gray, mac-style) -->
          <div style="
            display: flex; align-items: center; gap: 10px;
            padding: 14px 20px;
            background: #1c1c1c;
            border-bottom: 1px solid #2a2a2a;
          ">
            <div style="width: 14px; height: 14px; border-radius: 50%; background: #ff5f57;"></div>
            <div style="width: 14px; height: 14px; border-radius: 50%; background: #febc2e;"></div>
            <div style="width: 14px; height: 14px; border-radius: 50%; background: #28c840;"></div>
            <div style="
              flex: 1; text-align: center;
              font-family: var(--font-mono); font-size: 16px;
              color: #999;
              letter-spacing: 0.03em;
            ">~/projects/videowright-demo — claude — 160×48</div>
          </div>

          <!-- Claude Code TUI body — normal terminal background -->
          <div style="
            flex: 1;
            display: flex; flex-direction: column;
            padding: 32px 40px 28px;
            font-family: var(--font-mono);
            color: #e5e5e5;
            background: #0c0c0c;
            overflow: hidden;
          ">
            <!-- Claude Code banner -->
            <div style="
              display: flex; align-items: flex-start; gap: 22px;
              padding-bottom: 22px;
              border-bottom: 1px dashed #2a2a2a;
              margin-bottom: 28px;
            ">
              <pre style="
                margin: 0;
                font-family: var(--font-mono);
                font-size: 22px;
                line-height: 1.05;
                color: ${CLAUDE_ORANGE};
                text-shadow: 0 0 10px rgba(217, 119, 87, 0.4);
              ">${MASCOT}</pre>
              <div style="display: flex; flex-direction: column; gap: 4px; padding-top: 4px;">
                <div style="
                  font-family: var(--font-mono);
                  font-size: 24px;
                  color: ${CLAUDE_ORANGE};
                  font-weight: 500;
                ">✻ Welcome to Claude Code</div>
                <div style="
                  font-family: var(--font-mono);
                  font-size: 20px;
                  color: #888;
                ">cwd: ~/projects/videowright-demo</div>
              </div>
            </div>

            <!-- Conversation log -->
            <div style="
              flex: 1;
              font-size: 26px;
              line-height: 1.6;
              overflow: hidden;
            ">
              <div data-ref="user-block">
                <div style="color: #888;"><span style="color: ${CLAUDE_ORANGE};">&gt;</span> <span style="color: #e5e5e5;" data-ref="user-prompt"></span></div>
                <div style="
                  margin-top: 6px;
                  padding-left: 1.4em;
                  font-size: 22px;
                  color: #888;
                " data-ref="user-paste"></div>
              </div>

              <div data-ref="agent-block-1" style="margin-top: 26px; opacity: 0;">
                <div style="display: flex; gap: 14px; align-items: flex-start;">
                  <span style="color: ${CLAUDE_ORANGE}; flex-shrink: 0;">●</span>
                  <div style="flex: 1;">
                    <span data-ref="agent-text-1" style="color: #e5e5e5;"></span>
                  </div>
                </div>
                <div data-ref="working" style="
                  margin-top: 14px;
                  padding-left: 32px;
                  display: flex; align-items: center; gap: 14px;
                  font-size: 22px;
                  color: ${CLAUDE_ORANGE};
                  opacity: 0;
                ">
                  <span data-ref="spinner" style="display: inline-block; width: 1ch;"></span>
                  <span style="color: #ccc;">Drafting segments…</span>
                  <span style="color: #777; margin-left: 12px;">(esc to interrupt)</span>
                </div>
              </div>

              <div data-ref="agent-block-2" style="margin-top: 32px; opacity: 0;">
                <div style="display: flex; gap: 14px; align-items: flex-start;">
                  <span style="color: ${CLAUDE_ORANGE}; flex-shrink: 0;">●</span>
                  <div style="flex: 1;">
                    <span style="color: #9fc77a;">✓</span>
                    <span style="color: #e5e5e5;"> ${AGENT_RESPONSE_2}</span>
                  </div>
                </div>
              </div>
            </div>

            <!-- Input prompt at the bottom -->
            <div style="
              margin-top: 24px;
              border: 1px solid #2a2a2a;
              border-radius: 6px;
              padding: 16px 22px;
              display: flex; align-items: center; gap: 14px;
              background: #141414;
              font-size: 22px;
            ">
              <span style="color: ${CLAUDE_ORANGE};">&gt;</span>
              <span style="color: #5a5a5a;">Try "Edit the script" or "/help"</span>
              <span style="
                margin-left: auto;
                font-family: var(--font-mono);
                font-size: 16px;
                color: #666;
                letter-spacing: 0.03em;
              ">⏎ send  ⇧⏎ newline</span>
            </div>

            <!-- Footer status line -->
            <div style="
              margin-top: 12px;
              display: flex; gap: 22px;
              font-family: var(--font-mono);
              font-size: 16px;
              color: #666;
              letter-spacing: 0.02em;
            ">
              <span><span style="color: ${CLAUDE_ORANGE};">●</span> claude-opus-4-7</span>
              <span>~18.4k tokens</span>
              <span style="margin-left: auto;">? for help</span>
            </div>
          </div>
        </div>
      </div>
    `;

		// User prompt starts empty — types in during play(). Paste line is set
		// in play() as a beat AFTER the prompt finishes typing.
		const userPromptEl = el.querySelector('[data-ref="user-prompt"]') as HTMLElement;
		userPromptEl.textContent = "";
		const userPasteEl = el.querySelector('[data-ref="user-paste"]') as HTMLElement;
		userPasteEl.textContent = "";
	},

	async play(ctx) {
		const terminal = host?.querySelector('[data-ref="terminal"]') as HTMLElement;
		const userPromptEl = host?.querySelector('[data-ref="user-prompt"]') as HTMLElement;
		const userPasteEl = host?.querySelector('[data-ref="user-paste"]') as HTMLElement;
		const agentBlock1 = host?.querySelector('[data-ref="agent-block-1"]') as HTMLElement;
		const agentText1 = host?.querySelector('[data-ref="agent-text-1"]') as HTMLElement;
		const agentBlock2 = host?.querySelector('[data-ref="agent-block-2"]') as HTMLElement;
		const working = host?.querySelector('[data-ref="working"]') as HTMLElement;
		const spinner = host?.querySelector('[data-ref="spinner"]') as HTMLElement;

		const ease = "cubic-bezier(0.2, 0.8, 0.2, 1)";

		// Zoom transforms — the terminal is positioned via `left:50%; top:50%`
		// with `transform: translate(-50%, -50%)`. We override transform here to
		// add a translate+scale that focuses the camera on the user prompt area
		// + the immediately-following agent reply (so the spinner is in-frame
		// during the thinking hold).
		const zoomIn = "translate(-50%, -50%) translate(360px, 170px) scale(1.3)";
		const zoomOut = "translate(-50%, -50%) translate(0px, 0px) scale(1)";

		// Brief black frame, then cut-in.
		await ctx.hold(300);

		// Hard cut to terminal already zoomed in on the prompt + reply area.
		terminal.style.transform = zoomIn;
		terminal.style.opacity = "1";

		// Type the user prompt — short line, snappy cadence.
		const prompt = USER_PROMPT_TEXT;
		const typeStepMs = 600 / prompt.length;
		for (let i = 0; i <= prompt.length; i++) {
			if (ctx.signal.aborted) return;
			userPromptEl.textContent = prompt.slice(0, i);
			await ctx.hold(typeStepMs);
		}

		// Show the [Pasted 43 lines] indicator just after the prompt — reads as
		// "user attached a long script to their short ask".
		await ctx.hold(220);
		userPasteEl.textContent = USER_PROMPT_PASTE;

		// Brief natural beat after submitting, then the agent starts replying.
		await ctx.hold(450);

		// Agent reply text streams in (still zoomed — viewer reads ahead).
		agentBlock1.animate([{ opacity: 0 }, { opacity: 1 }], {
			duration: 200,
			easing: ease,
			fill: "forwards",
		});

		const text = AGENT_RESPONSE_1;
		const totalStreamMs = 900;
		const stepMs = totalStreamMs / text.length;
		for (let i = 0; i <= text.length; i++) {
			if (ctx.signal.aborted) return;
			agentText1.textContent = text.slice(0, i);
			await ctx.hold(stepMs);
		}

		// Spinner appears — this is the THINKING moment. Hold here (zoomed in)
		// so the viewer registers the "agent at work" state. This is the key
		// beat of the segment.
		working.animate([{ opacity: 0 }, { opacity: 1 }], {
			duration: 150,
			easing: ease,
			fill: "forwards",
		});
		const spinnerFrames = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"];
		const totalSpinMs = 3200;
		const spinStep = 80;
		const spinIters = Math.floor(totalSpinMs / spinStep);
		for (let i = 0; i < spinIters; i++) {
			if (ctx.signal.aborted) return;
			spinner.textContent = spinnerFrames[i % spinnerFrames.length];
			await ctx.hold(spinStep);
		}
		spinner.textContent = "";
		working.animate([{ opacity: 1 }, { opacity: 0 }], {
			duration: 150,
			easing: ease,
			fill: "forwards",
		});

		// Zoom out as the agent's final reply lands — pulls back to reveal the
		// full terminal and the "Video is ready" line.
		terminal.animate([{ transform: zoomIn }, { transform: zoomOut }], {
			duration: 600,
			easing: ease,
			fill: "forwards",
		});

		await ctx.hold(250);

		// Final line.
		agentBlock2.animate(
			[
				{ opacity: 0, transform: "translateY(6px)" },
				{ opacity: 1, transform: "translateY(0)" },
			],
			{ duration: 280, easing: ease, fill: "forwards" },
		);

		await ctx.hold(450);

		await ctx.waitForNext();
	},

	unmount() {
		host = null;
	},
});
