import { defineSegment } from "videowright";

let host: HTMLElement | null = null;

const MASCOT = `  ▐▛███▜▌
 ▝▜█████▛▘
   ▘▘ ▝▝`;

const USER_PROMPT = `I want to build a video explaining videowright. Here's the script:`;
const USER_PASTE = "[Pasted 43 lines]";
const AGENT_RESPONSE_1 = `Reading your script. I'll scaffold the timeline and draft segments — ping me if you want a different style than your past videos.`;
const AGENT_RESPONSE_2 = "Video is ready. Preview: npm run dev";

export default defineSegment({
	id: "em-cold-open",
	advances: [9.99],
	voiceover:
		"Everything in this video — including the terminal you're watching right now — was generated by Videowright. One prompt. No editor.",

	mount(el) {
		host = el;
		el.innerHTML = `
      <div data-ref="page" style="
        position: relative;
        height: 100%;
        background: var(--color-bg);
        color: var(--color-fg);
        font-family: var(--font-body);
        overflow: hidden;
      ">
        <!-- top hairline -->
        <div data-ref="rule-top" style="
          position: absolute;
          left: var(--safe-x);
          right: var(--safe-x);
          top: var(--safe-y);
          height: 1px;
          background: var(--color-border);
          transform-origin: left center;
          transform: scaleX(0);
        "></div>

        <!-- top label row -->
        <div style="
          position: absolute;
          left: var(--safe-x);
          right: var(--safe-x);
          top: calc(var(--safe-y) + 22px);
          display: flex;
          justify-content: space-between;
          font-family: var(--font-mono);
          font-size: 14px;
          letter-spacing: 0.18em;
          text-transform: uppercase;
          color: var(--color-muted);
        ">
          <div data-ref="label-l" style="opacity: 0;">Vol. 01 / Session Transcript</div>
          <div data-ref="label-r" style="opacity: 0;">Claude Code · 41ac</div>
        </div>

        <!-- terminal window, centered in the page -->
        <div data-ref="terminal-wrap" style="
          position: absolute;
          left: 50%;
          top: 50%;
          transform: translate(-50%, -50%);
          width: 1520px;
          height: 760px;
          opacity: 0;
        ">
          <div style="
            position: relative;
            width: 100%;
            height: 100%;
            background: var(--color-surface);
            border: 1px solid var(--color-fg);
            display: flex;
            flex-direction: column;
            overflow: hidden;
          ">
            <!-- title bar -->
            <div style="
              display: flex;
              align-items: center;
              gap: 12px;
              padding: 12px 18px;
              border-bottom: 1px solid var(--color-fg);
              background: var(--color-bg);
            ">
              <span style="width: 10px; height: 10px; border: 1px solid var(--color-fg); border-radius: 50%;"></span>
              <span style="width: 10px; height: 10px; border: 1px solid var(--color-fg); border-radius: 50%;"></span>
              <span style="width: 10px; height: 10px; border: 1px solid var(--color-fg); border-radius: 50%;"></span>
              <div style="
                flex: 1;
                text-align: center;
                font-family: var(--font-mono);
                font-size: 14px;
                letter-spacing: 0.06em;
                color: var(--color-muted);
              ">~/projects/videowright-demo &mdash; claude &mdash; 160&times;48</div>
              <span style="width: 60px;"></span>
            </div>

            <!-- TUI body -->
            <div style="
              flex: 1;
              display: flex;
              flex-direction: column;
              padding: 28px 36px 24px;
              font-family: var(--font-mono);
              color: var(--color-fg);
              overflow: hidden;
            ">
              <!-- Banner -->
              <div style="
                display: flex;
                align-items: flex-start;
                gap: 20px;
                padding-bottom: 18px;
                border-bottom: 1px solid var(--color-border);
                margin-bottom: 22px;
              ">
                <pre style="
                  margin: 0;
                  font-family: var(--font-mono);
                  font-size: 18px;
                  line-height: 1.05;
                  color: var(--color-accent);
                ">${MASCOT}</pre>
                <div style="display: flex; flex-direction: column; gap: 4px; padding-top: 2px;">
                  <div style="
                    font-family: var(--font-mono);
                    font-size: 20px;
                    color: var(--color-accent);
                    letter-spacing: 0.02em;
                  ">&#10027; Welcome to Claude Code</div>
                  <div style="
                    font-family: var(--font-mono);
                    font-size: 16px;
                    color: var(--color-muted);
                  ">cwd: ~/projects/videowright-demo</div>
                </div>
              </div>

              <!-- Conversation log -->
              <div style="
                flex: 1;
                font-size: 22px;
                line-height: 1.55;
                overflow: hidden;
              ">
                <div data-ref="user-block">
                  <div>
                    <span style="color: var(--color-accent);">&gt;</span>
                    <span data-ref="user-prompt" style="color: var(--color-fg);"></span>
                  </div>
                  <div data-ref="user-paste" style="
                    margin-top: 6px;
                    padding-left: 1.4em;
                    font-size: 18px;
                    color: var(--color-muted);
                  "></div>
                </div>

                <div data-ref="agent-block-1" style="margin-top: 22px; opacity: 0;">
                  <div style="display: flex; gap: 14px; align-items: flex-start;">
                    <span style="color: var(--color-accent); flex-shrink: 0;">&#9679;</span>
                    <div style="flex: 1;">
                      <span data-ref="agent-text-1" style="color: var(--color-fg);"></span>
                    </div>
                  </div>
                  <div data-ref="working" style="
                    margin-top: 12px;
                    padding-left: 28px;
                    display: flex;
                    align-items: center;
                    gap: 14px;
                    font-size: 18px;
                    color: var(--color-accent);
                    opacity: 0;
                  ">
                    <span data-ref="spinner" style="display: inline-block; width: 1ch;"></span>
                    <span style="color: var(--color-fg);">Drafting segments&hellip;</span>
                    <span style="color: var(--color-muted); margin-left: 12px;">(esc to interrupt)</span>
                  </div>
                </div>

                <div data-ref="agent-block-2" style="margin-top: 26px; opacity: 0;">
                  <div style="display: flex; gap: 14px; align-items: flex-start;">
                    <span style="color: var(--color-accent); flex-shrink: 0;">&#9679;</span>
                    <div style="flex: 1;">
                      <span style="color: var(--color-accent);">&#10003;</span>
                      <span style="color: var(--color-fg);"> ${AGENT_RESPONSE_2}</span>
                    </div>
                  </div>
                </div>
              </div>

              <!-- Input prompt -->
              <div style="
                margin-top: 18px;
                border: 1px solid var(--color-border);
                padding: 12px 18px;
                display: flex;
                align-items: center;
                gap: 12px;
                background: var(--color-bg);
                font-size: 18px;
              ">
                <span style="color: var(--color-accent);">&gt;</span>
                <span style="color: var(--color-muted);">Try &ldquo;Edit the script&rdquo; or &ldquo;/help&rdquo;</span>
                <span style="
                  margin-left: auto;
                  font-family: var(--font-mono);
                  font-size: 13px;
                  color: var(--color-muted);
                  letter-spacing: 0.06em;
                ">&#9166; send &nbsp; &#8679;&#9166; newline</span>
              </div>

              <!-- Footer status -->
              <div style="
                margin-top: 10px;
                display: flex;
                gap: 22px;
                font-family: var(--font-mono);
                font-size: 13px;
                color: var(--color-muted);
                letter-spacing: 0.04em;
              ">
                <span><span style="color: var(--color-accent);">&#9679;</span> claude-opus-4-7</span>
                <span>~18.4k tokens</span>
                <span style="margin-left: auto;">? for help</span>
              </div>
            </div>
          </div>
        </div>

        <!-- bottom hairline + folio -->
        <div data-ref="rule-bot" style="
          position: absolute;
          left: var(--safe-x);
          right: var(--safe-x);
          bottom: calc(var(--safe-y) - 22px);
          height: 1px;
          background: var(--color-border);
          transform-origin: left center;
          transform: scaleX(0);
        "></div>
        <div data-ref="folio" style="
          position: absolute;
          right: var(--safe-x);
          bottom: calc(var(--safe-y) - 50px);
          font-family: var(--font-mono);
          font-size: 13px;
          letter-spacing: 0.18em;
          text-transform: uppercase;
          color: var(--color-muted);
          opacity: 0;
        ">P. 01</div>
      </div>
    `;

		const userPromptEl = el.querySelector('[data-ref="user-prompt"]') as HTMLElement;
		userPromptEl.textContent = USER_PROMPT;
		const userPasteEl = el.querySelector('[data-ref="user-paste"]') as HTMLElement;
		userPasteEl.textContent = USER_PASTE;
	},

	async play(ctx) {
		const $ = (k: string) => host?.querySelector(`[data-ref="${k}"]`) as HTMLElement;
		const ease = "cubic-bezier(0.16, 1, 0.3, 1)";
		const fwd = { fill: "forwards" as const, easing: ease };

		// Page furniture
		$("rule-top").animate([{ transform: "scaleX(0)" }, { transform: "scaleX(1)" }], {
			...fwd,
			duration: 700,
		});
		$("rule-bot").animate([{ transform: "scaleX(0)" }, { transform: "scaleX(1)" }], {
			...fwd,
			duration: 700,
			delay: 80,
		});
		$("label-l").animate([{ opacity: 0 }, { opacity: 1 }], { ...fwd, duration: 480, delay: 320 });
		$("label-r").animate([{ opacity: 0 }, { opacity: 1 }], { ...fwd, duration: 480, delay: 380 });
		$("folio").animate([{ opacity: 0 }, { opacity: 1 }], { ...fwd, duration: 480, delay: 440 });

		// Terminal stamps in
		await ctx.hold(520);
		$("terminal-wrap").animate(
			[
				{ opacity: 0, transform: "translate(-50%, -50%) scale(0.97)" },
				{ opacity: 1, transform: "translate(-50%, -50%) scale(1)" },
			],
			{ ...fwd, duration: 360 },
		);

		await ctx.hold(1100);

		// Agent response appears and types in
		$("agent-block-1").animate([{ opacity: 0 }, { opacity: 1 }], { ...fwd, duration: 240 });
		const agentText1 = $("agent-text-1");
		const totalStreamMs = 2200;
		const stepMs = totalStreamMs / AGENT_RESPONSE_1.length;
		for (let i = 0; i <= AGENT_RESPONSE_1.length; i++) {
			if (ctx.signal.aborted) return;
			agentText1.textContent = AGENT_RESPONSE_1.slice(0, i);
			await ctx.hold(stepMs);
		}

		// Working spinner
		$("working").animate([{ opacity: 0 }, { opacity: 1 }], { ...fwd, duration: 180 });
		const spinner = $("spinner");
		const spinnerFrames = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"];
		const totalSpinMs = 1700;
		const spinStep = 90;
		const spinIters = Math.floor(totalSpinMs / spinStep);
		for (let i = 0; i < spinIters; i++) {
			if (ctx.signal.aborted) return;
			spinner.textContent = spinnerFrames[i % spinnerFrames.length];
			await ctx.hold(spinStep);
		}
		spinner.textContent = "";
		$("working").animate([{ opacity: 1 }, { opacity: 0 }], { ...fwd, duration: 180 });

		await ctx.hold(220);
		$("agent-block-2").animate(
			[
				{ opacity: 0, transform: "translateY(6px)" },
				{ opacity: 1, transform: "translateY(0)" },
			],
			{ ...fwd, duration: 280 },
		);

		await ctx.waitForNext();
	},

	unmount() {
		host = null;
	},
});
