import { defineSegment } from "videowright";

let host: HTMLElement | null = null;

const GRAIN_BG = `url(&quot;data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='200'><filter id='n'><feTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='2' stitchTiles='stitch'/><feColorMatrix values='0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.6 0'/></filter><rect width='100%25' height='100%25' filter='url(%23n)'/></svg>&quot;)`;

const SCRIPT_LINES = [
	"# cold-open",
	"Everything in this video — generated by Videowright.",
	"# title-card",
	"Videowright turns a coding agent into a video team.",
	"# voiceover-sync",
	"Your script generates the narration.",
	"# install-cta",
	"Paste a script into your coding agent.",
];

const EDITED_LINE_INDEX = 5;
const ORIGINAL_TEXT = "Your script generates the narration.";
const EDITED_TEXT = "Your script generates the narration. The narration drives timing.";

export default defineSegment({
	id: "rs-voiceover-sync",
	advances: [7.33],
	voiceover:
		"Your script generates the narration. The narration drives the timing. Edit a line — everything re-syncs.",

	mount(el) {
		host = el;
		el.innerHTML = `
      <div style="
        position: relative;
        height: 100%;
        background: var(--color-bg);
        color: var(--color-fg);
        font-family: var(--font-body);
        overflow: hidden;
        display: flex;
        gap: 40px;
        padding: 60px 80px 100px;
      ">
        <div style="
          position: absolute; inset: 0; pointer-events: none; z-index: 30;
          background-image: ${GRAIN_BG};
          opacity: var(--grain-opacity); mix-blend-mode: multiply;
        "></div>

        <div style="
          position: absolute;
          right: var(--safe-x); top: 60px;
          font-family: var(--font-display);
          font-size: 32px;
          color: var(--color-accent);
          transform: rotate(-3deg);
          z-index: 10;
        ">&#9733; 06/08 &#9733;</div>

        <!-- Left: script.md -->
        <div data-ref="script-wrap" style="
          flex: 1;
          position: relative;
          opacity: 0;
        ">
          <div style="
            position: absolute; inset: 0;
            transform: translate(var(--misreg), var(--misreg));
            background: var(--color-accent);
            mix-blend-mode: multiply;
            opacity: 0.55;
          "></div>
          <div style="
            position: relative;
            height: 100%;
            background: var(--color-bg);
            border: 3px solid var(--color-fg);
            display: flex; flex-direction: column;
            overflow: hidden;
          ">
            <div style="
              padding: 12px 18px;
              border-bottom: 3px solid var(--color-fg);
              font-family: var(--font-mono);
              font-size: 16px;
              font-weight: 600;
              letter-spacing: 0.08em;
              display: flex; align-items: center; gap: 14px;
            ">
              <span>voiceover/script.md</span>
              <span data-ref="status-chip" style="
                margin-left: auto;
                padding: 4px 10px;
                font-size: 12px;
                background: var(--color-fg);
                color: var(--color-bg);
                letter-spacing: 0.06em;
                opacity: 0;
              ">SYNCED &#10003;</span>
            </div>

            <div style="
              flex: 1;
              padding: 28px 32px;
              font-family: var(--font-mono);
              font-size: 20px;
              line-height: 1.7;
              color: var(--color-fg);
              overflow: hidden;
            " data-ref="script-body">
              ${SCRIPT_LINES.map((line, i) => {
								const isHeading = line.startsWith("#");
								return `<div data-line="${i}" style="
                position: relative;
                padding: 2px 8px;
                margin: 2px -8px;
                color: ${isHeading ? "var(--color-muted)" : "var(--color-fg)"};
                font-weight: ${isHeading ? 500 : 400};
              ">${isHeading ? `<span style="color: var(--color-accent);">${line.split(" ")[0]}</span> ${line.slice(line.indexOf(" ") + 1)}` : `<span data-line-text="${i}">${line}</span><span data-line-caret="${i}" style="display: none; color: var(--color-accent); font-weight: 700;">▌</span>`}</div>`;
							}).join("")}
            </div>
          </div>
        </div>

        <!-- Right: animation preview -->
        <div data-ref="preview-wrap" style="
          flex: 1;
          position: relative;
          opacity: 0;
        ">
          <div style="
            position: absolute; inset: 0;
            transform: translate(var(--misreg), var(--misreg));
            background: var(--color-accent);
            mix-blend-mode: multiply;
            opacity: 0.55;
          "></div>
          <div style="
            position: relative;
            height: 100%;
            background: var(--color-bg);
            border: 3px solid var(--color-fg);
            display: flex; flex-direction: column;
            overflow: hidden;
          ">
            <div style="
              padding: 12px 18px;
              border-bottom: 3px solid var(--color-fg);
              font-family: var(--font-mono);
              font-size: 16px;
              font-weight: 600;
              letter-spacing: 0.08em;
            ">preview &#183; voiceover-sync</div>

            <div style="
              flex: 1;
              padding: 40px;
              display: flex; flex-direction: column; justify-content: center; align-items: center;
              text-align: center;
            ">
              <div style="
                font-family: var(--font-mono);
                font-size: 14px;
                letter-spacing: 0.18em;
                font-weight: 600;
                color: var(--color-muted);
                margin-bottom: 12px;
              ">&#9733; CAPTION</div>
              <div data-ref="caption" style="
                font-family: var(--font-display);
                font-size: 56px;
                line-height: 1.05;
                color: var(--color-fg);
                max-width: 700px;
              ">${ORIGINAL_TEXT}</div>
              <div data-ref="caption-meta" style="
                font-family: var(--font-mono);
                font-size: 18px;
                color: var(--color-accent);
                font-weight: 700;
                margin-top: 22px;
              ">1.8s</div>
            </div>

            <!-- Scrubber -->
            <div style="
              padding: 14px 22px;
              border-top: 3px solid var(--color-fg);
              display: flex; align-items: center; gap: 14px;
            ">
              <div style="font-family: var(--font-mono); font-size: 14px; font-weight: 700;">00:11</div>
              <div style="
                flex: 1;
                height: 8px;
                background: var(--color-bg);
                border: 2px solid var(--color-fg);
                position: relative;
              ">
                <div data-ref="scrubber" style="
                  position: absolute;
                  left: 30%;
                  top: -3px;
                  width: 12px; height: 12px;
                  background: var(--color-accent);
                  border: 2px solid var(--color-fg);
                "></div>
                <div data-ref="play-cursor" style="
                  position: absolute;
                  left: 30%; top: -10px;
                  width: 2px; height: 26px;
                  background: var(--color-fg);
                "></div>
              </div>
              <div style="font-family: var(--font-mono); font-size: 14px; font-weight: 700;">01:14</div>
            </div>
          </div>
        </div>
      </div>
    `;
	},

	async play(ctx) {
		const scriptWrap = host?.querySelector('[data-ref="script-wrap"]') as HTMLElement;
		const previewWrap = host?.querySelector('[data-ref="preview-wrap"]') as HTMLElement;
		const caption = host?.querySelector('[data-ref="caption"]') as HTMLElement;
		const captionMeta = host?.querySelector('[data-ref="caption-meta"]') as HTMLElement;
		const statusChip = host?.querySelector('[data-ref="status-chip"]') as HTMLElement;
		const scrubber = host?.querySelector('[data-ref="scrubber"]') as HTMLElement;
		const playCursor = host?.querySelector('[data-ref="play-cursor"]') as HTMLElement;

		const stepEase = "steps(6, end)";
		const opts = { fill: "forwards" as const, easing: stepEase };

		scriptWrap.animate(
			[
				{ opacity: 0, transform: "translateX(-10px)" },
				{ opacity: 1, transform: "translateX(0)" },
			],
			{ ...opts, duration: 260 },
		);
		previewWrap.animate(
			[
				{ opacity: 0, transform: "translateX(10px)" },
				{ opacity: 1, transform: "translateX(0)" },
			],
			{ ...opts, duration: 260, delay: 80 },
		);

		await ctx.hold(360);

		// Highlight lines in sequence, syncing captions
		const lineIndexes = [1, 3, 5, 7];
		const captions = [
			"Everything in this video — generated by Videowright.",
			"Videowright turns a coding agent into a video team.",
			ORIGINAL_TEXT,
			"Paste a script into your coding agent.",
		];
		const perLine = 360;
		for (let i = 0; i < lineIndexes.length - 1; i++) {
			highlightLine(lineIndexes[i]);
			caption.textContent = captions[i];
			captionMeta.textContent = `${(1.2 + i * 0.4).toFixed(1)}s`;
			scrubber.animate([{ left: `${10 + i * 18}%` }, { left: `${28 + i * 18}%` }], {
				...opts,
				duration: perLine - 40,
			});
			playCursor.animate([{ left: `${10 + i * 18}%` }, { left: `${28 + i * 18}%` }], {
				...opts,
				duration: perLine - 40,
			});
			await ctx.hold(perLine);
		}
		clearHighlights();

		// Land on the editable line
		highlightLine(EDITED_LINE_INDEX);
		caption.textContent = ORIGINAL_TEXT;

		// Cursor blinks then edit happens
		await ctx.hold(280);
		const caret = host?.querySelector(`[data-line-caret="${EDITED_LINE_INDEX}"]`) as HTMLElement;
		caret.style.display = "inline";

		// Type the extra clause
		const lineTextEl = host?.querySelector(
			`[data-line-text="${EDITED_LINE_INDEX}"]`,
		) as HTMLElement;
		const extra = EDITED_TEXT.slice(ORIGINAL_TEXT.length);
		const extraStep = 950 / extra.length;
		for (let i = 0; i <= extra.length; i++) {
			if (ctx.signal.aborted) return;
			lineTextEl.textContent = ORIGINAL_TEXT + extra.slice(0, i);
			await ctx.hold(extraStep);
		}
		caret.style.display = "none";

		// RE-SYNCING chip
		statusChip.textContent = "RE-SYNCING…";
		statusChip.style.background = "var(--color-accent)";
		statusChip.style.color = "var(--color-bg)";
		statusChip.animate(
			[
				{ opacity: 0, transform: "translateY(-4px)" },
				{ opacity: 1, transform: "translateY(0)" },
			],
			{ ...opts, duration: 200 },
		);

		await ctx.hold(640);

		statusChip.textContent = "SYNCED ✓";
		statusChip.style.background = "var(--color-fg)";

		// Caption updates with new line + timing extended
		caption.textContent = EDITED_TEXT;
		captionMeta.textContent = "2.7s";

		// Scrubber visibly shifts to reflect new timing
		scrubber.animate([{ left: "82%" }, { left: "70%" }], { ...opts, duration: 320 });
		playCursor.animate([{ left: "82%" }, { left: "70%" }], { ...opts, duration: 320 });

		await ctx.waitForNext();
	},

	unmount() {
		host = null;
	},
});

function highlightLine(idx: number) {
	const el = host?.querySelector(`[data-line="${idx}"]`) as HTMLElement;
	if (!el) return;
	el.style.background = "var(--color-accent)";
	el.style.color = "var(--color-bg)";
}

function clearHighlights() {
	const lines = host?.querySelectorAll("[data-line]");
	if (lines) {
		for (const el of lines) {
			const e = el as HTMLElement;
			const i = Number.parseInt(e.getAttribute("data-line") || "0", 10);
			const isHeading = SCRIPT_LINES[i].startsWith("#");
			e.style.background = "transparent";
			e.style.color = isHeading ? "var(--color-muted)" : "var(--color-fg)";
		}
	}
}
