import { defineSegment } from "videowright";

let host: HTMLElement | null = null;

const LINES = [
	"Everything in this video — including the terminal you're watching right now — was generated by Videowright.",
	"This is Videowright. A library for building videos in your coding agent.",
	"Use any web technology — SVG, charts, three-D, real product UI.",
	"Iterate in chat. The dev server hot-reloads.",
	"One command renders a deterministic MP4. Frame by frame, pixel-exact.",
	"Your script generates the narration. The narration drives the timing.",
];

export default defineSegment({
	id: "em-voiceover-sync",
	advances: [7.33],
	voiceover:
		"Your script generates the narration. The narration drives the timing. Edit a line — everything re-syncs.",

	mount(el) {
		host = el;
		el.innerHTML = `
      <div style="
        position: relative;
        height: 100%;
        background: var(--color-bg);
        color: var(--color-fg);
        font-family: var(--font-body);
        overflow: hidden;
      ">
        <div style="position: absolute; left: var(--safe-x); right: var(--safe-x); top: var(--safe-y); height: 1px; background: var(--color-border);"></div>
        <div style="
          position: absolute;
          left: var(--safe-x);
          right: var(--safe-x);
          top: calc(var(--safe-y) + 22px);
          display: flex;
          justify-content: space-between;
          font-family: var(--font-mono);
          font-size: 14px;
          letter-spacing: 0.18em;
          text-transform: uppercase;
          color: var(--color-muted);
        ">
          <div>Plate / Voiceover</div>
          <div data-ref="state">script.md · synced</div>
        </div>

        <div style="
          position: absolute;
          left: var(--safe-x);
          right: var(--safe-x);
          top: 220px;
          bottom: var(--safe-y);
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 56px;
        ">
          <!-- LEFT: script -->
          <div>
            <div style="font-family: var(--font-mono); font-size: 13px; letter-spacing: 0.18em; text-transform: uppercase; color: var(--color-accent); margin-bottom: 24px;">A / voiceover/script.md</div>
            <div data-ref="script-list" style="display: flex; flex-direction: column; gap: 18px;">
              ${LINES.map(
								(l, i) => `
                <div data-ref="line-${i}" style="
                  display: grid;
                  grid-template-columns: 44px 1fr;
                  gap: 16px;
                  align-items: baseline;
                  font-family: var(--font-body);
                  font-size: 21px;
                  line-height: 1.4;
                  color: var(--color-muted);
                  padding: 8px 12px;
                  border-left: 2px solid transparent;
                  transition: color 200ms, background 200ms, border-color 200ms;
                ">
                  <span style="font-family: var(--font-mono); font-size: 13px; letter-spacing: 0.18em; color: var(--color-muted);">${String(i + 1).padStart(2, "0")}</span>
                  <span data-ref="line-text-${i}">${l}</span>
                </div>`,
							).join("")}
            </div>
          </div>

          <!-- RIGHT: preview -->
          <div>
            <div style="font-family: var(--font-mono); font-size: 13px; letter-spacing: 0.18em; text-transform: uppercase; color: var(--color-accent); margin-bottom: 24px;">B / Preview</div>
            <div style="
              border: 1px solid var(--color-fg);
              background: var(--color-bg);
              padding: 36px 44px 24px;
              display: flex;
              flex-direction: column;
              gap: 16px;
              min-height: 460px;
            ">
              <div style="font-family: var(--font-mono); font-size: 13px; letter-spacing: 0.18em; text-transform: uppercase; color: var(--color-muted);">Beat <span data-ref="beat-no">06</span> · <span data-ref="beat-t">00:47.2</span></div>
              <div data-ref="caption" style="font-family: var(--font-display); font-style: italic; font-size: 34px; line-height: 1.2; min-height: 130px;"></div>

              <div style="margin-top: auto; display: flex; flex-direction: column; gap: 10px;">
                <div style="display: flex; justify-content: space-between; font-family: var(--font-mono); font-size: 12px; color: var(--color-muted); letter-spacing: 0.12em; text-transform: uppercase;">
                  <span>Scrubber</span>
                  <span data-ref="sync-status" style="color: var(--color-fg);">SYNCED ✓</span>
                </div>
                <div style="height: 2px; background: var(--color-border); position: relative;">
                  <div data-ref="scrubber" style="position: absolute; left: 0; top: 0; bottom: 0; width: 0%; background: var(--color-accent);"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    `;
	},

	async play(ctx) {
		const $ = (k: string) => host?.querySelector(`[data-ref="${k}"]`) as HTMLElement;
		const ease = "cubic-bezier(0.16, 1, 0.3, 1)";
		const fwd = { fill: "forwards" as const, easing: ease };

		const scrubber = $("scrubber");
		const caption = $("caption");

		// scrubber runs through the segment
		scrubber.animate([{ width: "0%" }, { width: "85%" }], {
			...fwd,
			duration: 6500,
			easing: "linear",
		});

		// step through lines, highlighting each as "spoken"
		const lineDur = 700;
		let currentLine = -1;
		const highlightLine = (i: number) => {
			if (currentLine >= 0) {
				const prev = $(`line-${currentLine}`);
				prev.style.color = "var(--color-muted)";
				prev.style.background = "transparent";
				prev.style.borderLeftColor = "transparent";
			}
			const el = $(`line-${i}`);
			el.style.color = "var(--color-fg)";
			el.style.background = "var(--color-surface)";
			el.style.borderLeftColor = "var(--color-accent)";
			currentLine = i;
			caption.textContent = LINES[i];
		};

		for (let i = 0; i < 5; i++) {
			highlightLine(i);
			await ctx.hold(lineDur);
		}

		// hit line 5 — but trigger edit moment
		highlightLine(5);
		$("state").textContent = "EDITING…";

		await ctx.hold(220);

		// simulate a cursor edit: append " — automatically." to line 5
		const targetText =
			"Your script generates the narration. The narration drives the timing — automatically.";
		const lineText = $("line-text-5");
		// type the edit
		const original = LINES[5];
		const suffix = " — automatically.";
		await ctx.hold(120);

		for (let i = 0; i <= suffix.length; i++) {
			lineText.textContent = original + suffix.slice(0, i);
			caption.textContent = original + suffix.slice(0, i);
			await ctx.hold(28);
		}
		void targetText;

		// RE-SYNCING flash → SYNCED
		const status = $("sync-status");
		status.textContent = "RE-SYNCING…";
		status.style.color = "var(--color-accent)";
		$("state").textContent = "Re-syncing…";

		await ctx.hold(640);

		status.textContent = "SYNCED ✓";
		status.style.color = "var(--color-fg)";
		$("state").textContent = "script.md · synced";

		await ctx.waitForNext();
	},

	unmount() {
		host = null;
	},
});
