import { defineSegment } from "videowright";

let host: HTMLElement | null = null;

const CLAUDE_ORANGE = "#d97757";

const MASCOT = `  ▐▛███▜▌
 ▝▜█████▛▘
   ▘▘ ▝▝`;

const USER_PROMPT_TEXT = `I want to build a video explaining videowright. Here's the script:`;
const USER_PROMPT_PASTE = "[Pasted 43 lines]";
const AGENT_RESPONSE_1 = `Reading your script. I'll scaffold the timeline and draft segments — ping me if you want a different style than your past videos.`;
const AGENT_RESPONSE_2 = "Video is ready. Preview: npm run dev";

const GRAIN_BG = `url(&quot;data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='200'><filter id='n'><feTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='2' stitchTiles='stitch'/><feColorMatrix values='0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.6 0'/></filter><rect width='100%25' height='100%25' filter='url(%23n)'/></svg>&quot;)`;

export default defineSegment({
	id: "rs-cold-open",
	advances: [9.991],
	voiceover:
		"Everything in this video — including the terminal you're watching right now — was generated by Videowright. One prompt. No editor.",

	mount(el) {
		host = el;
		el.innerHTML = `
      <div style="
        position: relative;
        height: 100%;
        background: var(--color-bg);
        color: var(--color-fg);
        font-family: var(--font-body);
        overflow: hidden;
      ">
        <div style="
          position: absolute; inset: 0; pointer-events: none; z-index: 30;
          background-image: ${GRAIN_BG};
          opacity: var(--grain-opacity); mix-blend-mode: multiply;
        "></div>

        <div data-ref="lower-third" style="
          position: absolute;
          left: var(--safe-x); bottom: 56px;
          font-family: var(--font-display);
          font-size: 28px;
          color: var(--color-accent);
          letter-spacing: 0.02em;
          transform: rotate(-2deg);
          opacity: 0;
          z-index: 5;
        ">&#9733; scene 01 / 08 &#9733;</div>

        <div data-ref="corner-tag" style="
          position: absolute;
          right: var(--safe-x); top: 60px;
          font-family: var(--font-mono);
          font-size: 18px;
          color: var(--color-muted);
          letter-spacing: 0.18em;
          opacity: 0;
          z-index: 5;
        ">&#9670; INT. TERMINAL &#9670;</div>

        <!-- Terminal window — real Claude Code TUI rendering, framed by riso paper -->
        <div data-ref="terminal-wrap" style="
          position: absolute;
          left: 50%; top: 50%;
          transform: translate(-50%, -50%) rotate(-0.6deg);
          opacity: 0;
        ">
          <!-- pink misregistration ghost behind the window -->
          <div style="
            position: absolute;
            inset: 0;
            transform: translate(var(--misreg), var(--misreg));
            background: var(--color-accent);
            mix-blend-mode: multiply;
            opacity: 0.55;
            pointer-events: none;
          "></div>

          <div data-ref="terminal" style="
            position: relative;
            width: 1680px; height: 900px;
            background: #0c0c0c;
            border: 3px solid var(--color-fg);
            display: flex; flex-direction: column;
            overflow: hidden;
          ">
            <!-- Claude Code title bar with traffic lights -->
            <div style="
              display: flex; align-items: center; gap: 10px;
              padding: 14px 20px;
              background: #1c1c1c;
              border-bottom: 1px solid #2a2a2a;
            ">
              <div style="width: 14px; height: 14px; border-radius: 50%; background: #ff5f57;"></div>
              <div style="width: 14px; height: 14px; border-radius: 50%; background: #febc2e;"></div>
              <div style="width: 14px; height: 14px; border-radius: 50%; background: #28c840;"></div>
              <div style="
                flex: 1; text-align: center;
                font-family: var(--font-mono); font-size: 16px;
                color: #999;
                letter-spacing: 0.03em;
              ">~/projects/videowright-demo &mdash; claude &mdash; 160&times;48</div>
            </div>

            <!-- TUI body -->
            <div style="
              flex: 1;
              display: flex; flex-direction: column;
              padding: 32px 40px 28px;
              font-family: var(--font-mono);
              color: #e5e5e5;
              background: #0c0c0c;
              overflow: hidden;
            ">
              <!-- Banner: ASCII mascot + welcome -->
              <div style="
                display: flex; align-items: flex-start; gap: 22px;
                padding-bottom: 22px;
                border-bottom: 1px dashed #2a2a2a;
                margin-bottom: 28px;
              ">
                <pre style="
                  margin: 0;
                  font-family: var(--font-mono);
                  font-size: 22px;
                  line-height: 1.05;
                  color: ${CLAUDE_ORANGE};
                ">${MASCOT}</pre>
                <div style="display: flex; flex-direction: column; gap: 4px; padding-top: 4px;">
                  <div style="
                    font-family: var(--font-mono);
                    font-size: 24px;
                    color: ${CLAUDE_ORANGE};
                    font-weight: 500;
                  ">&#10027; Welcome to Claude Code</div>
                  <div style="
                    font-family: var(--font-mono);
                    font-size: 20px;
                    color: #888;
                  ">cwd: ~/projects/videowright-demo</div>
                </div>
              </div>

              <!-- Conversation log -->
              <div style="
                flex: 1;
                font-size: 26px;
                line-height: 1.6;
                overflow: hidden;
              ">
                <div data-ref="user-block">
                  <div style="color: #888;"><span style="color: ${CLAUDE_ORANGE};">&gt;</span> <span style="color: #e5e5e5;" data-ref="user-prompt"></span></div>
                  <div style="
                    margin-top: 6px;
                    padding-left: 1.4em;
                    font-size: 22px;
                    color: #888;
                  " data-ref="user-paste"></div>
                </div>

                <div data-ref="agent-block-1" style="margin-top: 26px; opacity: 0;">
                  <div style="display: flex; gap: 14px; align-items: flex-start;">
                    <span style="color: ${CLAUDE_ORANGE}; flex-shrink: 0;">&#9679;</span>
                    <div style="flex: 1;">
                      <span data-ref="agent-text-1" style="color: #e5e5e5;"></span>
                    </div>
                  </div>
                  <div data-ref="working" style="
                    margin-top: 14px;
                    padding-left: 32px;
                    display: flex; align-items: center; gap: 14px;
                    font-size: 22px;
                    color: ${CLAUDE_ORANGE};
                    opacity: 0;
                  ">
                    <span data-ref="spinner" style="display: inline-block; width: 1ch;"></span>
                    <span style="color: #ccc;">Drafting segments&hellip;</span>
                    <span style="color: #777; margin-left: 12px;">(esc to interrupt)</span>
                  </div>
                </div>

                <div data-ref="agent-block-2" style="margin-top: 32px; opacity: 0;">
                  <div style="display: flex; gap: 14px; align-items: flex-start;">
                    <span style="color: ${CLAUDE_ORANGE}; flex-shrink: 0;">&#9679;</span>
                    <div style="flex: 1;">
                      <span style="color: #9fc77a;">&#10003;</span>
                      <span style="color: #e5e5e5;"> ${AGENT_RESPONSE_2}</span>
                    </div>
                  </div>
                </div>
              </div>

              <!-- Input prompt -->
              <div style="
                margin-top: 24px;
                border: 1px solid #2a2a2a;
                padding: 16px 22px;
                display: flex; align-items: center; gap: 14px;
                background: #141414;
                font-size: 22px;
              ">
                <span style="color: ${CLAUDE_ORANGE};">&gt;</span>
                <span style="color: #5a5a5a;">Try &ldquo;Edit the script&rdquo; or &ldquo;/help&rdquo;</span>
                <span style="
                  margin-left: auto;
                  font-family: var(--font-mono);
                  font-size: 16px;
                  color: #666;
                  letter-spacing: 0.03em;
                ">&#9166; send &nbsp; &#8679;&#9166; newline</span>
              </div>

              <!-- Footer status -->
              <div style="
                margin-top: 12px;
                display: flex; gap: 22px;
                font-family: var(--font-mono);
                font-size: 16px;
                color: #666;
                letter-spacing: 0.02em;
              ">
                <span><span style="color: ${CLAUDE_ORANGE};">&#9679;</span> claude-opus-4-7</span>
                <span>~18.4k tokens</span>
                <span style="margin-left: auto;">? for help</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    `;

		const userPromptEl = el.querySelector('[data-ref="user-prompt"]') as HTMLElement;
		userPromptEl.textContent = USER_PROMPT_TEXT;
		const userPasteEl = el.querySelector('[data-ref="user-paste"]') as HTMLElement;
		userPasteEl.textContent = USER_PROMPT_PASTE;
	},

	async play(ctx) {
		const terminalWrap = host?.querySelector('[data-ref="terminal-wrap"]') as HTMLElement;
		const lowerThird = host?.querySelector('[data-ref="lower-third"]') as HTMLElement;
		const cornerTag = host?.querySelector('[data-ref="corner-tag"]') as HTMLElement;
		const agentBlock1 = host?.querySelector('[data-ref="agent-block-1"]') as HTMLElement;
		const agentText1 = host?.querySelector('[data-ref="agent-text-1"]') as HTMLElement;
		const agentBlock2 = host?.querySelector('[data-ref="agent-block-2"]') as HTMLElement;
		const working = host?.querySelector('[data-ref="working"]') as HTMLElement;
		const spinner = host?.querySelector('[data-ref="spinner"]') as HTMLElement;

		const stepEase = "steps(6, end)";
		const opts = { fill: "forwards" as const, easing: stepEase };

		// 0:00–0:01 — paper holds, very brief
		await ctx.hold(800);

		// Lower-third tag + corner mark stamp in
		lowerThird.animate(
			[
				{ opacity: 0, transform: "rotate(-2deg) translateY(8px)" },
				{ opacity: 1, transform: "rotate(-2deg) translateY(0)" },
			],
			{ ...opts, duration: 240 },
		);
		cornerTag.animate([{ opacity: 0 }, { opacity: 1 }], {
			...opts,
			duration: 200,
			delay: 80,
		});

		// Terminal stamps in
		terminalWrap.animate(
			[
				{ opacity: 0, transform: "translate(-50%, -50%) rotate(-0.6deg) scale(0.96)" },
				{ opacity: 1, transform: "translate(-50%, -50%) rotate(-0.6deg) scale(1)" },
			],
			{ ...opts, duration: 320, delay: 120 },
		);

		await ctx.hold(1200);

		// Agent response stamps in then types
		agentBlock1.animate([{ opacity: 0 }, { opacity: 1 }], {
			...opts,
			duration: 200,
		});

		const text = AGENT_RESPONSE_1;
		const totalStreamMs = 2200;
		const stepMs = totalStreamMs / text.length;
		for (let i = 0; i <= text.length; i++) {
			if (ctx.signal.aborted) return;
			agentText1.textContent = text.slice(0, i);
			await ctx.hold(stepMs);
		}

		// Working / spinner
		working.animate([{ opacity: 0 }, { opacity: 1 }], {
			...opts,
			duration: 160,
		});
		const spinnerFrames = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"];
		const totalSpinMs = 1800;
		const spinStep = 90;
		const spinIters = Math.floor(totalSpinMs / spinStep);
		for (let i = 0; i < spinIters; i++) {
			if (ctx.signal.aborted) return;
			spinner.textContent = spinnerFrames[i % spinnerFrames.length];
			await ctx.hold(spinStep);
		}
		spinner.textContent = "";
		working.animate([{ opacity: 1 }, { opacity: 0 }], {
			...opts,
			duration: 160,
		});

		await ctx.hold(220);
		agentBlock2.animate(
			[
				{ opacity: 0, transform: "translateY(8px)" },
				{ opacity: 1, transform: "translateY(0)" },
			],
			{ ...opts, duration: 280 },
		);

		await ctx.waitForNext();
	},

	unmount() {
		host = null;
	},
});
